title: Surfing the Cyber
author: _hyperlogic
description: > # this means to ignore newlines until "twitter_username:"
     Vulnerability research, network security, software development, and other tech ramblings.

# social links
twitter_username: _hyperlogic
github_username:  mellow-hype
rss: rss

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

markdown: kramdown
highlighter: rouge

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
